<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.7.0.0',
  'acceptable_sugar_versions' =>
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' =>
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'raw',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => false,
  'name' => 'Rating Star Field',
  'published_date' => '2017-10-21 12:43:07',
  'type' => 'module',
  'version' => time(),
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'copy' =>
	array (
	      0 =>
			array (
			  'from' => '<basepath>/custom/include/SugarFields/Fields/Rating/SugarFieldRatingfield.php',
			  'to' => 'custom/include/SugarFields/Fields/Rating/SugarFieldRatingfield.php',
			),
		  1 =>
			array (
			  'from' => '<basepath>/custom/include/javascript/sugar7/plugins/CssLoader.js',
			  'to' => 'custom/include/javascript/sugar7/plugins/CssLoader.js',
			),
		  2 =>
			array (
			  'from' => '<basepath>/custom/Extension/application/Ext/clients/base/filters/operators/StarRating.php',
			  'to' => 'custom/Extension/application/Ext/clients/base/filters/operators/StarRating.php',
			),
		  3 =>
			array (
			  'from' => '<basepath>/custom/Extension/application/Ext/JSGroupings/cssLoaderPlugin.php',
			  'to' => 'custom/Extension/application/Ext/JSGroupings/cssLoaderPlugin.php',
			),
		  4 =>
			array (
			  'from' => '<basepath>/custom/Extension/application/Ext/Language/en_us.Ratingfield.php',
			  'to' => 'custom/Extension/application/Ext/Language/en_us.Ratingfield.php',
			),
		  5 =>
			array (
			  'from' => '<basepath>/custom/Extension/modules/ModuleBuilder/Ext/Language/en_us.Ratingfield.php',
			  'to' => 'custom/Extension/modules/ModuleBuilder/Ext/Language/en_us.Ratingfield.php',
			),
		  6 =>
			array (
			  'from' => '<basepath>/custom/Extension/modules/DynamicFields/Ext/Language/en_us.Ratingfield.php',
			  'to' => 'custom/Extension/modules/DynamicFields/Ext/Language/en_us.Ratingfield.php',
			),
		  7 =>
			array (
			  'from' => '<basepath>/custom/modules/DynamicFields/templates/Fields/Forms/Ratingfield.php',
			  'to' => 'custom/modules/DynamicFields/templates/Fields/Forms/Ratingfield.php',
			),
		  8 =>
			array (
			  'from' => '<basepath>/custom/modules/DynamicFields/templates/Fields/Forms/Rating.tpl',
			  'to' => 'custom/modules/DynamicFields/templates/Fields/Forms/Rating.tpl',
			),
		  9 =>
			array (
			  'from' => '<basepath>/custom/modules/DynamicFields/templates/Fields/TemplateRatingfield.php',
			  'to' => 'custom/modules/DynamicFields/templates/Fields/TemplateRatingfield.php',
			),
		  10 =>
			array (
			  'from' => '<basepath>/custom/clients/base/fields/Ratingfield/edit.hbs',
			  'to' => 'custom/clients/base/fields/Ratingfield/edit.hbs',
			),
		  11 =>
			array (
			  'from' => '<basepath>/custom/clients/base/fields/Ratingfield/Ratingfield.js',
			  'to' => 'custom/clients/base/fields/Ratingfield/Ratingfield.js',
			),
		  12 =>
			array (
			  'from' => '<basepath>/custom/clients/base/fields/Ratingfield/detail.hbs',
			  'to' => 'custom/clients/base/fields/Ratingfield/detail.hbs',
			),
		  13 =>
			array (
			  'from' => '<basepath>/custom/clients/base/fields/Ratingfield/list.hbs',
			  'to' => 'custom/clients/base/fields/Ratingfield/list.hbs',
			),
		  14 =>
			array (
			  'from' => '<basepath>/custom/themes/star_rating.css',
			  'to' => 'custom/themes/star_rating.css',
			),
  ),
);

